FROM oven/bun:1.3.14-slim AS base
WORKDIR /usr/src/api

# === Dependencies Stage ===
FROM base AS dependencies
COPY package.json bun.lock ./
RUN bun ci

# === Building Stage ===
FROM dependencies AS building
COPY --chown=bun:bun prisma/ ./prisma/
COPY --chown=bun:bun prisma.config.ts ./

ENV POSTGRES_URL="postgresql://dummy:dummy@localhost:5432/dummy"
RUN bun run prisma:generate

# === Migrations Stage ===
FROM building AS migrations
CMD ["bun", "run", "prisma:migrate"]

# === Development Stage ===
FROM building AS development
COPY --chown=bun:bun . .
USER bun

EXPOSE 3000
CMD ["bun", "run", "start:dev"]
